version: '2'
services:
  web:
    container_name: go-memo
    build: .
    restart: always
    ports:
      - "8008:8008"
    volumes:
      - ./conf:/app/conf
    environment:
      GO_MEMO_WORKDIR: /app
      service_env: production
      gin_env: production
      GIN_MODE: release
    networks:
      - memo

  memo_db:
    image: mysql:5.7
    container_name: memo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zs
      MYSQL_USER: zs
      MYSQL_PASSWORD: zs
    volumes:
      - ./build/db/data:/var/lib/mysql
      - ./build/db/config:/etc/mysql
    ports:
      - 3306:3306
    networks:
      - memo

networks:
  memo: